site_name: Project Books Docs
edit_uri: docs/edit/main/docs
repo_name: GitHub
repo_url: https://github.com/Project-Books
nav:
  - Home: index.md
  - Contributing: contributing.md
  - Code of Conduct: code-of-conduct.md
  - Style Guides:
          - Java Style Guide: styleguides/java-styleguide.md
          - React Style Guide: styleguides/react-styleguide.md
          - TypeScript Style Guide: styleguides/typescript-styleguide.md
  - Maintaining:
          - Code reviews: maintaining/code-reviews.md
          - Code of conduct resolutions: maintaining/code-of-conduct-resolutions.md
          - Becoming a maintainer: maintaining/maintainer.md
          - Becoming a triager: maintaining/triager.md
theme:
        name: material
        palette:
            # Light side
            - media: "(prefers-color-scheme: light)"
              primary: white
              accent: red
              toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to the dark side

            # Dark side
            - media: "(prefers-color-scheme: dark)"
              primary: black
              accent: red
              toggle:
                icon: material/toggle-switch
                name: Switch to the light side

        icon:
            repo: octicons/mark-github-16

        favicon: images/favicon.png

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/teambookproject/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A
      name: Book Project Slack Workspace
