site_name: Project Books Docs
edit_uri: docs/edit/main/docs
repo_name: GitHub
repo_url: https://github.com/Project-Books
nav:
  - Home: index.md
  - UI/UX Design:
          - Design: design/join-design-team.md
          - Design team: design/design-team.md
  - Development:
          - Contributing: development/contributing.md
          - Style Guides:
                  - Java Style Guide: development/styleguides/java-styleguide.md
                  - React Style Guide: development/styleguides/react-styleguide.md
                  - TypeScript Style Guide: development/styleguides/typescript-styleguide.md
          - How to:
                  - Connect to the backend with Postman: development/how-to/backend-postman.md
                  - Rewriting pushed commits with a different email address: development/how-to/rewrite-pushed-commits.md
                  - Troubleshoot: development/how-to/troubleshoot.md
          - Maintaining:
                  - Becoming a maintainer: development/maintaining/maintainer.md
                  - Becoming a triager: development/maintaining/triager.md
                  - Code reviews: development/maintaining/code-reviews.md
                  - Core team: development/maintaining/core-team.md
  - Conduct:
          - Code of Conduct: code-of-conduct.md
          - Code of conduct resolutions: code-of-conduct-resolutions.md
  - About:
        - Core principles: core-principles.md
        - FAQ: faq.md
        - Vision: vision.md

theme:
        name: material
        palette:
            # Light side
            - media: "(prefers-color-scheme: light)"
              primary: white
              accent: red
              toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to the dark side

            # Dark side
            - media: "(prefers-color-scheme: dark)"
              primary: black
              accent: red
              toggle:
                icon: material/toggle-switch
                name: Switch to the light side

        icon:
            repo: octicons/mark-github-16

        favicon: images/favicon.png

markdown_extensions:
  - toc:
      permalink: True

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/teambookproject/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A
      name: Book Project Slack Workspace
